export type Ton = "success" | "warning" | "danger" | "info" | "neutral";

const TON_PO_STATUSU: Record<string, Ton> = {
  PRIHVACEN: "success",
  PRIHVACENO: "success",
  POTVRDJENA: "success",
  URADJENO: "success",
  PASS: "success",
  SPREMNO: "success",
  DOSTUPNO: "success",
  ZATVORENA: "success",
  PROSAO: "success",
  VAZI: "success",

  CEKA_ODLUKU: "warning",
  U_TOKU: "warning",
  U_PRIPREMI: "warning",
  DJELIMICNO_PRIHVACEN: "warning",
  DJELIMICNA: "warning",
  HOLD: "warning",
  KARANTIN: "warning",
  WARNING: "warning",
  USKORO: "warning",
  MJERA_U_TOKU: "warning",
  CEKA_VERIFIKACIJU: "warning",
  OTVOREN: "warning",
  PLANIRANO: "warning",

  ODBIJEN: "danger",
  ODBIJENA: "danger",
  ODBIJI: "danger",
  FAIL: "danger",
  NIJE_SPREMNO: "danger",
  BLOKIRANO: "danger",
  ISTEKLO: "danger",
  ISTEKAO: "danger",
  ISTEKLA: "danger",
  NIJE_PROSAO: "danger",
  KASNI: "danger",
  OTVORENA: "danger",
  ZAKASNIO: "danger",
  VISOK: "danger",

  REZERVISANO: "info",
  U_ISTRAZI: "info",
  ISTRAGA: "info",
  SREDNJI: "info",

  OTKAZAN: "neutral",
  OTKAZANA: "neutral",
  NIZAK: "neutral",
  PONOVO_OTVORENA: "warning",
};

const NAZIVI: Record<string, string> = {
  PRIHVACEN: "Prihvaćen",
  PRIHVACENO: "Prihvaćeno",
  PRIHVACENA: "Prihvaćena",
  CEKA_ODLUKU: "Čeka odluku",
  DJELIMICNO_PRIHVACEN: "Djelimično prihvaćen",
  DJELIMICNA: "Djelimična",
  ODBIJEN: "Odbijen",
  ODBIJENA: "Odbijena",
  U_TOKU: "U toku",
  U_PRIPREMI: "U pripremi",
  POTVRDJENA: "Potvrđena",
  HOLD: "Na čekanju (HOLD)",
  KARANTIN: "Karantin",
  PRIMLJEN: "Primljen",
  ISTEKAO: "Istekao",
  ISTROSEN: "Istrošen",
  DOSTUPNO: "Dostupno",
  BLOKIRANO: "Blokirano",
  ISTEKLO: "Isteklo",
  SPREMNO: "Spremno",
  NIJE_SPREMNO: "Nije spremno",
  PASS: "Prošlo",
  FAIL: "Van opsega",
  WARNING: "Blizu granice",
  PROSAO: "Prošao",
  NIJE_PROSAO: "Nije prošao",
  OTVORENA: "Otvorena",
  ISTRAGA: "Istraga",
  POTREBNA_MJERA: "Potrebna mjera",
  MJERA_U_TOKU: "Mjera u toku",
  CEKA_VERIFIKACIJU: "Čeka verifikaciju",
  ZATVORENA: "Zatvorena",
  PONOVO_OTVORENA: "Ponovo otvorena",
  OTVOREN: "Otvoren",
  ZAVRSEN: "Završen",
  ZAKASNIO: "Zakasnio",
  OTKAZAN: "Otkazan",
  URADJENO: "Urađeno",
  USKORO: "Uskoro",
  KASNI: "Kasni",
  PLANIRANO: "Planirano",
  VAZI: "Važi",
  ISTEKLA: "Istekla",
  NEPOZNATO: "Nepoznato",
  VISOK: "Visoka",
  SREDNJI: "Srednja",
  NIZAK: "Niska",
};

export function StatusBadge({ status, tekst }: { status: string; tekst?: string }) {
  const ton = TON_PO_STATUSU[status] ?? "neutral";
  return (
    <span className={`status-badge ${ton}`}>
      <span />
      {tekst ?? NAZIVI[status] ?? status}
    </span>
  );
}
